[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  command = "npm install"
  publish = "."

# Bật CORS đơn giản khi dev local với Netlify CLI
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
